DROP DATABASE IF EXISTS pi_idev4_2026_1;
CREATE DATABASE IF NOT EXISTS pi_idev4_2026_1;
USE pi_idev4_2026_1;

CREATE TABLE IF NOT EXISTS equipes (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL,
codigo LONGTEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS participantes (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS equipes_participantes (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
id_participante  INT NOT NULL ,
id_equipe INT NOT NULL ,
FOREIGN KEY (id_participante) REFERENCES participantes(id),
FOREIGN KEY (id_equipe) REFERENCES equipes(id)
);



CREATE TABLE IF NOT EXISTS pistas (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL,
id_equipe INT NULL,
foreign key (id_equipe) references equipes(id)
);

CREATE TABLE IF NOT EXISTS corridas (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS dados_corridas (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
id_corrida INT NULL,
id_equipe INT NULL,
tempo_volta TIME NULL,
hora_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (id_corrida) REFERENCES corridas(id),
FOREIGN KEY (id_equipe) REFERENCES equipes(id)
);

CREATE TABLE IF NOT EXISTS podiums (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
id_corrida INT NULL,
id_equipe INT NULL,
total_voltas INT NOT NULL,
melhor_volta TIME NOT NULL,
tempo_ultima_volta TIME NOT NULL,
velocidade_media FLOAT NOT NULL,
posicao INT NOT NULL,
FOREIGN KEY (id_corrida) REFERENCES corridas(id),
FOREIGN KEY (id_equipe) REFERENCES equipes(id)
);
